version: '3'

services:
  webproxy:
    image: nginx:stable
    container_name: proxy-nginx 
    ports:
      - 80:80
      - 443:443
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/certbot/conf/:/etc/nginx/ssl/:ro
      - ./data/certbot/www:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./data/certbot/conf/:/etc/letsencrypt/:rw
      - ./data/certbot/www/:/var/www/certbot/:rw
#comentario:
# el volumen ./nginx.conf:/etc/nginx/conf.d/default.conf:ro puede reemplazarse por dos archivos separados
#uno que configure el back y otro el front basta que este dentro de la carpeta conf.d y nginx lo va a ejecutar
# - ./backend.conf:/etc/nginx/conf.d/backend.conf:ro