version: '3'

services:
  webproxy:
    image: nginx:stable
    container_name: proxy-nginx 
    ports:
      - 80:80
      - 443:443
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginxbasic.conf:/etc/nginx/conf.d/default.conf:ro        
#recuerda ponerle nombre a las imagenes
#container_name: proxy-nginx
#container_name: cerbot
#prueba quitar el network_mode: bridge en teoria es el valor por defecto